<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ul4</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~U</string>
	<key>name</key>
	<string>UL4</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)\s*(ul4|for|while|if|elif|else|break|continue|return|code|printx?)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.ul4</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.ul4</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.ul4</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.inline.other.ul4</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.ul4</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.ul4</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.ul4</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.ul4</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;\?)\s*(whitespace)\s+(keep|strip|smart)\s*(\?&gt;)</string>
			<key>name</key>
			<string>meta.function.inline.other.ul4</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)\s*(def)\s+([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.ul4</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.ul4</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.ul4</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.ul4</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.inline.template.ul4</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.ul4</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.ul4</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.ul4</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.ul4</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;\?)\s*(end)\s+(for|if|def)?\s*(\?&gt;)</string>
			<key>name</key>
			<string>meta.function.inline.other.ul4</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;\?\s*note.*\?&gt;</string>
			<key>name</key>
			<string>comment.ul4</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-function-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#float</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer-dec</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer-hex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer-oct</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer-bin</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#color</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>color</key>
		<dict>
			<key>match</key>
			<string>#([0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b</string>
			<key>name</key>
			<string>constant.other.color.ul4</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(None|True|False)\b</string>
			<key>name</key>
			<string>constant.language.ul4</string>
		</dict>
		<key>date</key>
		<dict>
			<key>match</key>
			<string>@\([0-9]{4}-[0-9]{2}-[0-9]{2}(T([0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{6})?)?)?)?\)</string>
			<key>name</key>
			<string>constant.other.date.ul4</string>
		</dict>
		<key>float</key>
		<dict>
			<key>match</key>
			<string>[+-]?(?=\d*[.eE])(?=\.?\d)\d*\.?\d*(?:[eE][+-]?\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.float.ul4</string>
		</dict>
		<key>function</key>
		<dict>
			<key>match</key>
			<string>(abs|all|any|asjson|asul4on|bin|bool|ceil|chr|cos|csv|date|enumerate|enumfl|exp|first|float|floor|format|fromjson|fromul4on|hex|hls|hsv|int|isbool|iscolor|isdate|isdefined|isdict|isfirst|isfirstlast|isfloat|isfunction|isint|islast|islist|ismonthdelta|isnone|isset|isstr|istemplate|istimedelta|isundefined|last|len|list|log|max|min|monthdelta|now|oct|ord|pi|pow|print|printx|randchoice|random|randrange|range|repr|reversed|rgb|round|set|sin|slice|sorted|sqrt|str|sum|tan|tau|timedelta|type|urlquote|urlunquote|utcnow|xmlescape|zip)</string>
			<key>name</key>
			<string>support.function.ul4</string>
		</dict>
		<key>integer-bin</key>
		<dict>
			<key>match</key>
			<string>\b(?i:0b[01]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.binary.ul4</string>
		</dict>
		<key>integer-dec</key>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.ul4</string>
		</dict>
		<key>integer-hex</key>
		<dict>
			<key>match</key>
			<string>\b(?i:0x[0-9a-f]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.hexadecimal.ul4</string>
		</dict>
		<key>integer-oct</key>
		<dict>
			<key>match</key>
			<string>\b(?i:0o[0-7]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.octal.ul4</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(for|in|not|and|or|if|else)\b</string>
			<key>name</key>
			<string>keyword.ul4</string>
		</dict>
		<key>method</key>
		<dict>
			<key>match</key>
			<string>(add|append|capitalize|day|days|endswith|find|get|hour|insert|isoformat|items|join|lower|lstrip|microsecond|microseconds|mimeformat|minute|month|pop|replace|rfind|rsplit|rstrip|second|seconds|split|startswith|strip|update|upper|values|week|weekday|year|yearday)</string>
			<key>name</key>
			<string>support.other.method.ul4</string>
		</dict>
		<key>name</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\_][a-zA-Z\_0-9]*)</string>
			<key>name</key>
			<string>variable.ul4</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>\b(\+=|-=|\*=|\/\/=|\/=|%=|&lt;&lt;=|&gt;&gt;=|&amp;=|\^=|\|=|:|\.|\*\*|\*|=|\-|\+|\/\/|\/|%|&lt;&lt;|&gt;&gt;|&amp;|\^|\||==|!=|&lt;=|&lt;|&gt;=|&gt;)\b</string>
			<key>name</key>
			<string>keyword.operator.ul4</string>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ul4</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ul4</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.ul4</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-escape</string>
				</dict>
			</array>
		</dict>
		<key>string-escape</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\x[0-9a-fA-F]{2}</string>
					<key>name</key>
					<string>constant.character.escape.8bit.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u[0-9a-fA-F]{4}</string>
					<key>name</key>
					<string>constant.character.escape.16bit.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\U[0-9a-fA-F]{8}</string>
					<key>name</key>
					<string>constant.character.escape.32bit.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\a</string>
					<key>name</key>
					<string>constant.character.escape.bell.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\b</string>
					<key>name</key>
					<string>constant.character.escape.backspace.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\t</string>
					<key>name</key>
					<string>constant.character.escape.tab.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\n</string>
					<key>name</key>
					<string>constant.character.escape.newline.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\f</string>
					<key>name</key>
					<string>constant.character.escape.formfeed.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\r</string>
					<key>name</key>
					<string>constant.character.escape.return.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\"</string>
					<key>name</key>
					<string>constant.character.escape.double-quote.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\'</string>
					<key>name</key>
					<string>constant.character.escape.single-quote.ul4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\\\</string>
					<key>name</key>
					<string>constant.character.escape.backlash.ul4</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ul4</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ul4</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.ul4</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-escape</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ul4</string>
	<key>uuid</key>
	<string>62CF888C-5D46-45E4-B98F-DC16FF5374A9</string>
</dict>
</plist>
