<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ul4</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~U</string>
	<key>name</key>
	<string>ul4</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;\?)\s*(whitespace|ul4|for|while|if|elif|else|def|end|break|continue|return|code|printx?|note)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.ul4</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.ul4</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.ul4</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.inline.other.ul4</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>color</key>
		<dict>
			<key>match</key>
			<string>#([0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b</string>
			<key>name</key>
			<string>constant.other.color.ul4</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(None|True|False)\b</string>
			<key>name</key>
			<string>constant.language.ul4</string>
		</dict>
		<key>date</key>
		<dict>
			<key>match</key>
			<string>@\([0-9]{4}-[0-9]{2}-[0-9]{2}(T([0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]{6})?)?)?)?\)</string>
			<key>name</key>
			<string>constant.other.date.ul4</string>
		</dict>
		<key>float</key>
		<dict>
			<key>match</key>
			<string>[+-]?(?=\d*[.eE])(?=\.?\d)\d*\.?\d*(?:[eE][+-]?\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.float.ul4</string>
		</dict>
		<key>integer</key>
		<dict>
			<key>match</key>
			<string>\b([0-9]+|0[xX][0-9a-fA-F]+|0[oO][0-7]+|0[bB][01]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.ul4</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(for|in|not|and|or|if|else)\b</string>
			<key>name</key>
			<string>keyword.ul4</string>
		</dict>
		<key>name</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z\_][a-zA-Z\_0-9]*)</string>
			<key>name</key>
			<string>entity.other.attribute-name.html</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>\b(\+=|-=|\*=|\/\/=|\/=|%=|&lt;&lt;=|&gt;&gt;=|&amp;=|\^=|\|=|:|\.|\*\*|\*|=|\-|\+|\/\/|\/|%|&lt;&lt;|&gt;&gt;|&amp;|\^|\||==|!=|&lt;=|&lt;|&gt;=|&gt;)\b</string>
			<key>name</key>
			<string>keyword.operator.ul4</string>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entities</string>
				</dict>
			</array>
		</dict>
		<key>tag-id-attribute</key>
		<dict>
			<key>begin</key>
			<string>\b(id)\b\s*(=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.id.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;='|")</string>
			<key>name</key>
			<string>meta.attribute-with-value.id.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.toc-list.id.html</string>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#entities</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-function-name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#float</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#integer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#color</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#date</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ul4</string>
	<key>uuid</key>
	<string>62CF888C-5D46-45E4-B98F-DC16FF5374A9</string>
</dict>
</plist>
